#%RAML 1.0 Trait

queryParameters:
      number1:
        required: true
        type: integer
      number2:
        required: true
        type: integer
responses:            
      404:
        body:
          application/json:
            example:
              {
                "message": "method not allowed"
              }
      500:
        body:
          application/json:
            example:
              {
                "message": "internal server error"
              }      